### ISSUE TITLE
Trivia rating fails to update after game ends

### ISSUE THREAD

**Issue by andreijl** [theLAZYmd/LAZYbot#87]
Here the error log:

019-08-05T03:03:23.870Z | [31merror[39m: TypeError: Cannot read property 'username' of undefined
    at /home/ubuntu/LAZYbot/src/modules/Trivia/trivia.js:168:42
    at Array.filter (<anonymous>)
    at Trivia.ratingUpdate (/home/ubuntu/LAZYbot/src/modules/Trivia/trivia.js:166:20)
    at Function.run (/home/ubuntu/LAZYbot/src/util/commands.js:25:86)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Function.run (/home/ubuntu/LAZYbot/src/router/message.js:63:4)
    at async module.exports (/home/ubuntu/LAZYbot/src/router/message.js:109:18)
019-08-05T00:52:36.301Z | [31merror[39m: read ECONNRESET
019-08-05T00:31:37.333Z | [31merror[39m: read ECONNRESET
019-08-04T23:47:34.938Z | [31merror[39m: TypeError: Cannot read property 'username' of undefined
    at /home/ubuntu/LAZYbot/src/modules/Trivia/trivia.js:168:42
    at Array.filter (<anonymous>)
    at Trivia.ratingUpdate (/home/ubuntu/LAZYbot/src/modules/Trivia/trivia.js:166:20)
    at Function.run (/home/ubuntu/LAZYbot/src/util/commands.js:25:86)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Function.run (/home/ubuntu/LAZYbot/src/router/message.js:63:4)
    at async module.exports (/home/ubuntu/LAZYbot/src/router/message.js:109:18)

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/theLAZYmd/LAZYbot/commit/9187f5f83c0c1422c33d0264c5a35a101c8fa292
