### ISSUE TITLE
happens with !botcontingencyplan

### ISSUE THREAD

**Issue by iamthelaminator** [theLAZYmd/LAZYbot#89]
019-08-05T15:32:34.795Z | [31merror[39m: Error: Couldn't find module ./src/modules/Utility/states
    at Function.run (/home/ubuntu/LAZYbot/src/util/commands.js:20:39)
    at Function.run (/home/ubuntu/LAZYbot/src/router/message.js:63:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/home/ubuntu/LAZYbot/src/router/message.js:126:6)

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/theLAZYmd/LAZYbot/commit/c20bd0aeba4ba47ff8db9e452e17c8cf194c5dc2
