### ISSUE TITLE
happens with !election

### ISSUE THREAD

**Issue by iamthelaminator** [theLAZYmd/LAZYbot#90]
019-08-05T15:40:41.346Z | [31merror[39m: Error: Couldn't find module ./src/modules/Election/election
    at Function.run (/home/ubuntu/LAZYbot/src/util/commands.js:20:39)
    at Function.run (/home/ubuntu/LAZYbot/src/router/message.js:63:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/home/ubuntu/LAZYbot/src/router/message.js:126:6)

**Comment by theLAZYmd** [comment]
https://github.com/theLAZYmd/LAZYbot/commit/c117aa7d4751996163b897598bc731b4b3872b8f
